// Turns the catalogue into the seeding migration. Pure, so a test can compare its output with the
// committed file and stop the two drifting apart.
import type { CatalogEntry } from './entry.ts'

/** Where the generated migration lives (relative to the project root). */
export const CATALOG_MIGRATION_FILE = 'supabase/migrations/20260928000200_expanded_catalog.sql'

const quote = (text: string) => `'${text.replace(/'/g, "''")}'`
const pgArray = (items: string[]) => quote(`{${items.join(',')}}`)

const row = (e: CatalogEntry) =>
  `    (${quote(e.name)}, ${quote(e.category)}, ${quote(e.tracking)}, ${pgArray(e.primary_muscles)}, ${pgArray(e.secondary_muscles)}, ` +
  `${quote(e.equipment)}, array[${e.instructions.map(quote).join(', ')}])`

export function renderCatalogMigration(entries: readonly CatalogEntry[]): string {
  return `-- GENERATED by scripts/build-catalog-migration.ts from src/config/catalog. Do not edit by hand:
-- change the catalogue files and regenerate.
-- FitPip / expanded starter catalogue: ${entries.length} more exercises (single-arm cable work, plate-loaded and
-- pin-loaded machines, barbell and Olympic lifts, dumbbells and kettlebells, bodyweight and TRX, carries, sleds,
-- cardio, conditioning, track running, swimming, boxing, sports and classes).
-- Paste into the Supabase SQL Editor and run. Safe to re-run.
--
-- Needs 20260926000100_more_activities.sql to have been run first. Existing accounts get the new rows
-- below, new accounts get them with the rest of the starter bank, and the "Load starter exercises" button
-- in Settings fills in anything missing. Same-name rows are skipped, so nothing you edited or added is touched.

create or replace function public.starter_activity_catalog_extra()
returns table (
  name              text,
  category          text,
  tracking          text,
  primary_muscles   public.muscle[],
  secondary_muscles public.muscle[],
  equipment         public.equipment_type,
  instructions      text[]
)
language sql
immutable
set search_path = ''
as $$
  select
    v.name,
    v.category,
    v.tracking,
    v.primary_muscles::public.muscle[],
    v.secondary_muscles::public.muscle[],
    v.equipment::public.equipment_type,
    v.instructions
  from (values
${entries.map(row).join(',\n')}
  ) as v (name, category, tracking, primary_muscles, secondary_muscles, equipment, instructions)
$$;

revoke all on function public.starter_activity_catalog_extra() from public, anon, authenticated;

-- Adds any missing starter activities (the original set, the first extras and this expansion) for one user.
create or replace function public.seed_starter_activities(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted integer;
begin
  insert into public.exercises
    (user_id, name, category, tracking, primary_muscles, secondary_muscles, equipment, instructions)
  select
    p_user_id, a.name, a.category, a.tracking, a.primary_muscles, a.secondary_muscles,
    a.equipment, a.instructions
  from (
    select * from public.starter_activity_catalog()
    union all
    select * from public.starter_activity_catalog_more()
    union all
    select * from public.starter_activity_catalog_extra()
  ) a
  on conflict do nothing;

  get diagnostics inserted = row_count;
  return inserted;
end;
$$;

revoke all on function public.seed_starter_activities(uuid) from public, anon, authenticated;

-- Existing accounts get the new exercises now.
do $$
declare
  u record;
begin
  for u in select id from auth.users loop
    perform public.seed_starter_activities(u.id);
  end loop;
end $$;
`
}
