// Generated by npm run icons. Content hashes give changed artwork a fresh URL.
export const appIcons = {
  "standard192": "/icons/icon-192-074d4e7fa392.png",
  "standard512": "/icons/icon-512-d0a8aa10fb8b.png",
  "maskable512": "/icons/icon-maskable-512-9ea277b0fd29.png",
  "appleTouch": "/apple-touch-icon-565b945dd6ad.png",
  "favicon": "/favicon-dcb096603eac.png"
} as const
