/**
 * What Pip (the red-panda mascot) says. One line is dealt per app launch, and tapping Pip deals
 * another; every line is shown once before any repeat (see lib/pipDeck.ts). Add freely: the deck
 * reshuffles itself when the list changes length.
 */
export const PIP_LINES: readonly string[] = [
  // Getting started
  "Oh hey, you're back! I was just stretching my tail.",
  'The hardest rep is opening the app. You already did it.',
  'Small steps still count. Even tiny paw-sized ones.',
  "Let's make future you say thank you.",
  "Warm up first. I'm not scooping you off the floor.",
  "Today's plan: show up, do the thing, feel smug.",
  "Five minutes. Just start with five minutes. I'll wait.",
  'You showed up. That already beats yesterday-you on the couch.',
  "Pick one thing and do it well. That's the whole secret.",
  "Consistency beats intensity. Also, snacks beat nothing. But mostly consistency.",
  // Lifting
  'Lift heavy, rest well, repeat. Easy to say, fun to do.',
  'Progressive overload: one more rep or one more plate than last time.',
  'Squats are just sitting down with ambition.',
  "The bar doesn't care about your excuses. Rude, but fair.",
  "Leave one rep in the tank. You'll need it for the stairs later.",
  "Brace your core like someone's about to poke your belly.",
  'Slow on the way down. Your muscles love the scenic route.',
  'Chalk is not a personality trait. But it is fun.',
  'Rest days are when the muscle actually shows up to work.',
  "Heavy day? I'll count. One... two... I only have little paws.",
  'Deadlift day is back-in-business day.',
  'Your only competition is last week-you. Last week-you was good. Be better.',
  'Log it or it didn’t happen. That’s the rule.',
  // Cardio
  "Run like there's a free snack at the finish line.",
  "Easy runs should feel easy. If you can't talk, you're sprinting, silly.",
  'Hearts are muscles too. Give yours some reps.',
  'A slow mile is still faster than no mile.',
  'Hills are just the ground asking for a hug.',
  'Rowing: the only place going backwards counts as progress.',
  'Jump rope makes everyone feel like a boxer. Even me.',
  'Bike day! Helmet on, legs spinning, wind in your fur.',
  "Intervals: go hard, breathe, repeat. Complaining is optional.",
  'Walks count. Every step is a tiny victory lap.',
  'Take the stairs today. Tiny wins add up to big ones.',
  // Swimming
  'Swim day! I’ll hold your towel. I can’t swim. Red pandas climb.',
  'Long strokes, slow breaths. Glide like a sleepy otter.',
  'Pool rule number one: never skip leg day in the water either.',
  'Freestyle is free. The lane rental is not. Make it count.',
  'Every lap is a lap. Even the ones where you forgot to count.',
  // Yoga and stretching
  "Breathe in... breathe out... okay, now hold it. The pose, not the breath.",
  "Downward dog? I'm more of a downward panda.",
  'Flexibility is a slow game. Your hamstrings are listening.',
  "Tree pose tip: pick a spot on the wall and stare at it like it owes you money.",
  "Stretch after training. Future you's back sends its regards.",
  "Savasana is still yoga. It's the best pose. I've mastered it.",
  "Don't bounce in your stretches. Just melt into them.",
  'Tight hips? Pigeon pose is calling.',
  'Mobility today, fewer creaky noises tomorrow.',
  'Warrior II: arms strong, gaze steady, legs quietly on fire.',
  // Boxing
  "Hands up, chin down. And keep that tail tucked.",
  "Jab, cross, hook. Then hydrate. That's my favourite combo.",
  "The heavy bag never hits back. Enjoy it while it lasts.",
  "Move your feet! Sitting ducks don't win rounds.",
  "Three minutes can feel like forever. That's how you know it's working.",
  'Boxing is dancing, but angrier.',
  // Recovery and life
  "Sleep is the cheapest supplement. I take a lot of it.",
  'Water. Drink some. Right now. I’ll wait.',
  'Protein, veggies, sleep. Repeat until strong.',
  "Sore today? That's your body writing a thank-you note.",
  "Rest isn't quitting. It's loading the next level.",
  'Recovery walks are sneaky good.',
  'Some days are 100%. Some days are 40%. Both days count.',
  "Listen to your body. Unless it's asking for a sixth cookie.",
  "Missed a day? That's okay. Missing two is a pattern. Let's not.",
  'Bamboo is my protein. What’s yours?',
  // Weigh-ins
  'The scale is one number, not the whole story.',
  "Weigh in at the same time each morning. The scale likes routines too.",
  'Weight goes up and down daily. Watch the trend, not the wiggle.',
  "Strength goes up even when the scale stays still. Sneaky, right?",
  // Pep and silliness
  "You're stronger than you were last month. I checked. Okay, I guessed. But I believe it.",
  'Nobody ever regretted a workout. Well, maybe burpees. But not really.',
  "I'd high-five you, but my arms are very short.",
  'Tail wags for every set you finish.',
  "Today's forecast: 100% chance of gains.",
  "If you need me, I'll be here. Motivating. Adorably.",
  "Let's go! Or, you know, let's stretch and then go.",
  "Muscles don't grow in the gym. They grow on the couch afterwards. Earn the couch.",
  "You're not behind. You're exactly where you started, plus everything you did since.",
  'Fun fact: red pandas train by climbing trees. You have a gym. Lucky.',
  "Deep breath. Shoulders down. You've got this.",
  'Be the kind of tired that feels good.',
  "Personal record day? I've got my party hat on.",
  'Every champion was once a beginner who kept showing up.',
  "Some reps are ugly. They still count.",
  "Earn the snooze. Then snooze. That's balance.",
  "Plans are nice. Doing the plan is nicer.",
  'Mix it up! Lift, swim, stretch, box. Bodies love variety.',
  "Three things today: move, eat something green, go to bed on time.",
  "You versus you. That's the only match that matters.",
  "Don't count the days. Make the days count. I stole that one.",
  "Consistency is boring. Boring is powerful.",
  "One more set? One more set.",
] as const
