/**
 * What Pip says while he is in each pose or doing each gesture, so the words match what he is
 * doing: a flex sounds like strength, a yawn like rest, a stretch like mobility. Keep every line
 * under 110 characters. Each bank is dealt like a shuffled deck (lib/pip/voice.ts).
 */
import type { PipMood } from '../../components/pip/types'

export const MOOD_LINES: Record<PipMood, readonly string[]> = {
  idle: [
    'Hi. I was doing very serious panda thinking.',
    "Big day or small day, you're still on the team.",
    "I stretched my tail. Ready when you are.",
    "Fun fact: I can't lift anything. I'm strictly emotional support.",
    'Some days the win is just showing up. Today can be that day.',
    "I'm not saying I believe in you. I'm saying I've been saving your spot on the bench.",
    'Whatever the plan is, do the first five minutes. The rest follows.',
    'Hydrate. Then hydrate more. Then lift.',
    'My favourite exercise is the one you actually do.',
    'Plan the work, work the plan, high-five the panda.',
    'I like it here. Snacks, lifts, occasional cheering.',
    'Progress is quiet. It shows up as one more rep on a Tuesday.',
    'No pressure. Just a friendly reminder that future you is watching.',
    'Warm-up sets are free. Take them.',
  ],
  cheer: [
    "Somebody's about to lift heavy things. I can feel it!",
    'Today is a good day to set a personal best!',
    "You've got the energy. Let's spend it!",
    'Legs ready? Arms ready? Attitude ready? Go!',
    "I'm so excited I'm bouncing on the inside too.",
    'Big lifts, big smiles. That is the formula.',
    "The bar is waiting. It's being very dramatic about it.",
    'Ten reps? Ten reps! I believe in you and in the number ten.',
    "Every set you finish is a set nobody can take back.",
    "Yes! That's the energy! Bottle it!",
    "Show the weights who's boss. Politely.",
    "You don't need motivation. You need to start. Then I'll cheer.",
    'Today\'s mood: unstoppable, with a water break.',
    "Look at you go! I'm running out of exclamation marks!",
  ],
  sleep: [
    'Zzz... five more reps... I mean five more minutes.',
    'Zzz... oh! I was dreaming about a perfect squat.',
    'Rest is a workout too. I take it very seriously.',
    'Shh. Muscles are being built. Do not disturb.',
    'In my dream I lifted a whole bamboo forest.',
    'Snoring is just recovery with sound effects.',
    "Sleep is the cheapest supplement, and I'm a huge fan.",
    'Recovery mode: on. Guilt: off.',
    "A good night's sleep beats an extra set. Every time.",
    'Zzz... progress... zzz... protein... zzz...',
    'Naps are cardio for the brain. Trust me.',
    'You worked hard. Let today be soft.',
    'Rest days are when the gains file their paperwork.',
    'Eight hours sounds like a lot until you feel it.',
  ],
  think: [
    "Hmm. What if the hard set goes first, while we're fresh?",
    'Thinking about your week. It looks good. Suspiciously good.',
    "Do you push more or pull more? Let's keep the two in balance.",
    'Hmm. Has anyone stretched their hips lately? Asking for a panda.',
    "What's one thing you'd love to do better this month?",
    "If you could add one rep anywhere today, where would it go?",
    "The best program is the one you'll do. Hmm. That's deep.",
    'Heavy, or higher reps? Both are okay. Pick one and mean it.',
    "Let me calculate... yes: you're doing great. Maths checks out.",
    "I'm thinking about protein. And bamboo. Mostly protein.",
    'Trend, not wiggle. That is my entire scale philosophy.',
    "Hmm. Which muscle hasn't seen you lately?",
    "Ask yourself: am I resting enough for this much lifting?",
    'Pro tip I just made up: write down your first set, then beat it.',
  ],
  wave: [
    'Hey you! Good to see you.',
    'Back already? I love that for us.',
    'Hello, hello! The gym missed you. Well, I did.',
    "Hi! I'd shake your hand but... short arms.",
    "Look who's here! My favourite lifter.",
    'Hey! Ready for a good one?',
    'Welcome back. I saved you the good spot.',
    "Hi hi hi! Okay, I'm calm. Hi.",
    'Right on time. I love a punctual lifter.',
    "Hey, friend. How's the body feeling today?",
    'Oh hi! I was just telling the dumbbells about you.',
    "Hello! Reminder: you're allowed to enjoy this.",
    'Hey! Bring water. Bring snacks. Bring yourself.',
    'See you at the rack. Save me a plate. A small one.',
  ],
  bounce: [
    "Boing! That's me doing cardio.",
    "I can't sit still. Something good is about to happen!",
    'Jump, jump, jump! Okay, done. Cardio complete.',
    'Bounce first, ask questions later.',
    'Energy check: high. Panda check: bouncy.',
    'Nothing beats that first-set feeling. Boing!',
    'Fun fact: bouncing burns calories. I made that up, but it feels true.',
    'Springs in my feet, plans in my head!',
    'Ready, set... boing!',
    "I'm calling it: today's a good day for intervals.",
    "Hop to it! I've been waiting all morning to say that.",
    'Jump rope is just bouncing with a purpose.',
    "Come on, let's get that heart rate up a little!",
    "Boing boing. That's the sound of consistency.",
  ],
  love: [
    "I'm really glad you're doing this. For you, mostly. And also me.",
    'Thank you for showing up. I notice.',
    'You take care of yourself, and that makes me so happy.',
    "You're doing better than you think. I keep the receipts.",
    "Whatever today brings, I'm proud of you.",
    'Hugs for good sets, hugs for bad sets, hugs for rest days.',
    'Be kind to your body. It carries you everywhere.',
    "You don't have to be perfect. You just have to come back.",
    "You're building something that lasts. Slowly, and on purpose.",
    'I like it here. Mostly because of you.',
    "Small paws, big feelings: I'm rooting for you.",
    'Look how far you have come. Really look.',
    "Nobody's counting your reps but me, and I'm a fan.",
    'Soft heart, strong back. That is the goal.',
  ],
  celebrate: [
    'Confetti! Metaphorical, but still confetti.',
    'You did a thing. A great thing. I have a party hat.',
    'Personal record energy detected!',
    'Victory lap! Two hops, one spin, zero shame.',
    'That deserves a little happy dance.',
    'Achievement unlocked: showing up. Achievement also unlocked: doing the thing.',
    'Look at you, making the scoreboard nervous.',
    "Today's headline: local lifter beats last week.",
    "Proud of you doesn't cover it. But it's a start.",
    'Cue the trumpets. Small ones. I own small trumpets.',
    'Every finished workout is a win. Save it for a rainy day.',
    'Frame this moment. Then go have a snack.',
    'The plates are applauding. Very quietly. They are plates.',
    'Big smiles for big reps!',
  ],
  stretch: [
    'Reach tall... exhale... your hamstrings say hi.',
    'Ahhh. A good stretch is a tiny holiday.',
    "Breathe into the tight spot. Don't force it. Invite it.",
    "Hips first, always. They're grumpy from all that sitting.",
    'Hold each stretch for at least 30 seconds. Count in panda seconds.',
    'Shoulders down, neck long. Better already.',
    'Your upper back stiffens fast. Give it a gentle arch over a foam roller.',
    'Stretching after lifting feels good, and that is reason enough.',
    'Ankle mobility is secretly the key to a deeper squat.',
    'Cat-cow is basically a spine massage. Take five.',
    'Stand up. Reach. Yawn. You are welcome.',
    'A few slow breaths and your whole back lets go.',
    'A calf stretch on a stair step. Chef\'s kiss.',
    'Warm-ups move. Cool-downs hold. Pick the right one.',
  ],
  dance: [
    'Cardio is just dancing with a purpose.',
    'Put on the song that makes you walk faster.',
    'Left, right, left, right... panda shimmy!',
    'Keep moving. The music will figure it out.',
    'Dance breaks count as cardio. I checked with myself.',
    'Heart rate up, worries down.',
    'The treadmill has a beat if you listen closely.',
    'Try 30 seconds hard, 30 seconds easy. Then dance the rest.',
    'The best cardio is the kind you forget is cardio.',
    'Zone 2 is a groove: steady, easy, a little hypnotic.',
    'Rower rhythm: legs, back, arms. Arms, back, legs. That is a dance.',
    'Tap your foot. Now tap the other foot. That is warming up.',
    'Everybody has a shuffle in them. Find yours.',
    'One more song. Then one more.',
  ],
  peekaboo: [
    'Peekaboo! Did you weigh in today?',
    'Peekaboo! Did you drink some water?',
    'I see you! Have you stretched yet?',
    'Peekaboo! Log that set before you forget it.',
    "Found you! Time to pick today's first exercise.",
    "Peekaboo. Are you eating enough protein? Just checking.",
    "I'm hiding from the burpees. Don't tell them.",
    'There you are! I was looking for a motivated person.',
    'Look who is still here, still trying. Peekaboo!',
    "Boo! That's just me, reminding you to breathe.",
    'Peekaboo! Shoulders down, please.',
    'Where is your water bottle? Peekaboo, found it!',
    "I can see you thinking about skipping. Peekaboo. Don't.",
    "Psst. The scale is not scary. It's just a number.",
  ],
  flex: [
    "Behold: the bicep. It's small but it's mine.",
    'Feel the power. Okay, feel the potential.',
    'Strength is built one rep at a time. Flex on the last one.',
    'Squeeze at the top of every rep. It is free intensity.',
    'Mind-muscle connection: think about the muscle, not the weight.',
    "Big lifts first. Little lifts when you're tired. That's the order.",
    "Heavy is relative. Everything is heavy for a panda.",
    "Brace. Breathe. Push. That's strength.",
    'Flexing after a set is just data collection.',
    'Muscle is expensive for your body to keep. Keep it anyway.',
    'Slow lowering builds more than fast lifting. Lift slow.',
    "Track it, beat it. That's the whole gym.",
    'Get stronger and everything else gets easier.',
    'Stronger than yesterday? Then it was a good day.',
  ],
  nod: [
    'Yes. Control the lowering. Yes.',
    'Exactly. Chest up, core tight, eyes forward.',
    "That's right: full range of motion beats heavy junk reps.",
    'Nod nod. Warm up, work up, wind down.',
    'Yes, rest between sets. Two minutes is not wasted.',
    'Mm-hm. One more rep than last time. Small steps.',
    "Correct. Track every set: it's how we know we're winning.",
    "Yes, that's smart. Leave one rep in the tank.",
    'Agreed! Consistency beats intensity.',
    'Yes! Eat protein, sleep, repeat.',
    'I approve of this plan. Formally.',
    'Elbows tucked, shoulder blades back. Yes.',
    "You listen to your body. That's the most advanced skill in the gym.",
    "Nod of approval: filed under 'good decisions'.",
  ],
  yawn: [
    "Sleep is a performance-enhancing drug, and it's legal.",
    '*yawn* Sorry. Just thinking about how good rest days are.',
    'Sore? Sleep. Water. A walk. Repeat.',
    'Big lifts, big naps. That is the panda way.',
    "If you're tired, go easy. Showing up tired still counts.",
    "Recovery isn't lazy. It's where the strength shows up.",
    'Early to bed, early to lift. Or late to lift. Just sleep.',
    'Rest between sets, rest between days. Rest is in the plan.',
    'Yawning is contagious. Now you are doing it too.',
    'Caffeine is nice. Sleep is nicer.',
    'A 20-minute nap, a glass of water and a stretch: the holy trinity.',
    'Tight from yesterday? Walk it out.',
    'Screens off, lights low, muscles thank you tomorrow.',
    "Listen to your body. It's whispering 'nap'.",
  ],
}
