// Builds the starter-exercise SQL migration from ExerciseDB data.
//
//   node scripts/build-starter-seed.ts            regenerate the SQL from the cached records
//   node scripts/build-starter-seed.ts --refresh  re-download the picked records first
//
// scripts/starter-picks.json lists the exact ExerciseDB names in the starter bank.
// supabase/seed/exercisedb-starter.json caches their raw API records, so a normal run makes
// no network calls. --refresh is throttled because the free instance rate-limits bursts.
// Data: https://github.com/ExerciseDB/exercisedb-api (free instance oss.exercisedb.dev)
import { readFileSync, writeFileSync } from 'node:fs'
import { isImportable, mapExerciseDb, type ExerciseDbExercise } from '../src/config/exerciseDbMap.ts'

const API = 'https://oss.exercisedb.dev/api/v1/exercises'
const PICKS: string[] = JSON.parse(readFileSync('scripts/starter-picks.json', 'utf8'))
const CACHE = 'supabase/seed/exercisedb-starter.json'
const OUT = 'supabase/migrations/20260921000210_starter_exercise_catalog.sql'

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

async function fetchByName(name: string): Promise<ExerciseDbExercise> {
  for (let attempt = 1; attempt <= 6; attempt++) {
    const res = await fetch(`${API}?name=${encodeURIComponent(name)}&limit=25`)
    if (res.status === 429) {
      await sleep(5000 * attempt)
      continue
    }
    if (!res.ok) throw new Error(`ExerciseDB returned HTTP ${res.status} for "${name}"`)
    const json = (await res.json()) as { data: ExerciseDbExercise[] }
    const exact = json.data.find((e) => e.name === name)
    if (!exact) throw new Error(`No exact ExerciseDB match for "${name}"`)
    return exact
  }
  throw new Error(`Rate limited too long while fetching "${name}"`)
}

async function loadRecords(): Promise<ExerciseDbExercise[]> {
  if (!process.argv.includes('--refresh')) return JSON.parse(readFileSync(CACHE, 'utf8'))
  const records: ExerciseDbExercise[] = []
  for (const name of PICKS) {
    records.push(await fetchByName(name))
    await sleep(1200)
  }
  writeFileSync(CACHE, JSON.stringify(records, null, 1) + '\n')
  return records
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const list = (a: string[]) => q(`{${a.join(',')}}`)

const records = await loadRecords()
const mapped = PICKS.map((name) => {
  const record = records.find((r) => r.name === name)
  if (!record) throw new Error(`"${name}" is in starter-picks.json but not in ${CACHE}; run with --refresh`)
  const m = mapExerciseDb(record)
  if (!isImportable(m)) throw new Error(`"${name}" maps to no tracked muscle`)
  return m
})

const rows = mapped.map(
  (m) =>
    `    (${q(m.external_id)}, ${q(m.name)}, ${list(m.primary_muscles)}, ${list(m.secondary_muscles)}, ` +
    `${q(m.equipment)}, ${m.image_url ? q(m.image_url) : 'null'}, array[${m.instructions.map(q).join(', ')}])`,
)

writeFileSync(
  OUT,
  `-- GENERATED by scripts/build-starter-seed.ts from ExerciseDB data. Do not edit by hand:
-- change scripts/starter-picks.json or src/config/exerciseDbMap.ts and regenerate.
-- Source: https://github.com/ExerciseDB/exercisedb-api (free instance oss.exercisedb.dev).
-- Paste into the Supabase SQL Editor and run. Safe to re-run.

create or replace function public.starter_exercise_catalog()
returns table (
  external_id       text,
  name              text,
  primary_muscles   public.muscle[],
  secondary_muscles public.muscle[],
  equipment         public.equipment_type,
  image_url         text,
  instructions      text[]
)
language sql
immutable
set search_path = ''
as $$
  select
    v.external_id,
    v.name,
    v.primary_muscles::public.muscle[],
    v.secondary_muscles::public.muscle[],
    v.equipment::public.equipment_type,
    v.image_url,
    v.instructions
  from (values
${rows.join(',\n')}
  ) as v (external_id, name, primary_muscles, secondary_muscles, equipment, image_url, instructions)
$$;

revoke all on function public.starter_exercise_catalog() from public, anon, authenticated;

-- Give every existing account the starter bank (no-op for a brand-new project).
select public.seed_starter_exercises(id) from auth.users;
`,
)
console.log(`wrote ${mapped.length} exercises to ${OUT}`)
