import { createHash } from 'node:crypto'
import { copyFile, mkdir, readFile, readdir, unlink, writeFile } from 'node:fs/promises'
import sharp from 'sharp'

// The selected Focused close-up, with its dark navy background, is the source
// for every launcher asset and the README preview. Regeneration is fully local.
const source = await readFile(new URL('./art/pip-focused-dark.png', import.meta.url))

await mkdir('public/icons', { recursive: true })
await mkdir('docs/images', { recursive: true })
// Only remove files owned by this generator; keep the unversioned aliases for
// older installed app shells and Safari's root-directory fallback.
for (const directory of ['public', 'public/icons']) {
  for (const file of await readdir(directory)) {
    if (/^(?:favicon|apple-touch-icon|icon-192|icon-512|icon-maskable-512)-[a-f0-9]{12}\.png$/.test(file)) {
      await unlink(`${directory}/${file}`)
    }
  }
}
const render = async (size, output, inset = 0) => {
  let image = sharp(source).resize(size - inset * 2, size - inset * 2)
  if (inset) image = image.extend({ top: inset, bottom: inset, left: inset, right: inset, extendWith: 'copy' })
  const png = await image.png({ compressionLevel: 9 }).toBuffer()
  const revision = createHash('sha256').update(png).digest('hex').slice(0, 12)
  const versioned = output.replace(/\.png$/, `-${revision}.png`)
  await writeFile(versioned, png)
  await writeFile(output, png)
  return versioned.replace(/^public/, '')
}
const standard192 = await render(192, 'public/icons/icon-192.png')
const standard512 = await render(512, 'public/icons/icon-512.png')
// A tiny inset protects the smile inside Android's safe area; repeated edge
// pixels keep the close-up full bleed without adding a visible frame.
const maskable512 = await render(512, 'public/icons/icon-maskable-512.png', 4)
const appleTouch = await render(180, 'public/apple-touch-icon.png')
const favicon = await render(64, 'public/favicon.png')
const icons = { standard192, standard512, maskable512, appleTouch, favicon }
await writeFile('src/config/appIcons.ts',
  `// Generated by npm run icons. Content hashes give changed artwork a fresh URL.\nexport const appIcons = ${JSON.stringify(icons, null, 2)} as const\n`)
await copyFile('public/icons/icon-192.png', 'docs/images/fitpip-mobile-icon.png')
console.log('Focused Pip launcher, maskable, Apple touch, favicon and README preview written')
